From: John Levine <john.levine@standcore.com>
To: "${name}" <$addr>
Subject: RFC Editor satisfaction survey for ${month}
Mime-Version: 1.0
Content-Type: text/plain; charset=utf-8
Content-Transfer-Encoding: 8bit

This is a survey for authors and shepherds of recently published RFCs.  We've sent you this
because you are:

${rfcs}

We'd appreciate it if you'd complete a short survey about how we did.  
Start the survey here: ${url}

If you authored or shepherded more than one RFC, you can do the survey again,
or in the comments say what applies to which RFC.  Thanks.

Regards,
John Levine acting/interim RSE
